<?php
$this->form->prepare();
$form->setAttribute('action', $this->url('proveedores', ['action' => 'add']));
$this->form->setAttribute('class', 'form-horizontal');
$this->form->setAttribute('role', 'form');
?>

<div class="panel panel-default">
    <h1 class="text-center"><?= $this->titulo ?></h1>
    <div class="panel-body">
        <?= $this->form()->openTag($form); ?>        
        <?= $this->formElement($form->get('csrf')); ?>        

        <div class="form-group">
            <?= $this->formLabel($form->get('nombre')); ?>
            <?= $this->formElement($form->get('nombre')); ?>
            <?= $this->formElementErrors($form->get('nombre')); ?>   
            <median class="form-text font-weight-bold text-danger text-center">  

            </median>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('rut')); ?>
            <?= $this->formElement($form->get('rut')); ?>
            <?= $this->formElementErrors($form->get('rut')); ?> 
            <median id='mRut' class="form-text font-weight-bold text-danger text-center">

            </median>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-5">
                <?= $this->formSubmit($form->get('send')) ?>
            </div>
        </div>
        <?= $this->form()->closeTag() ?>
    </div>
</div>