<!--<strong>Module:</strong>        ZendSkeletonModule &raquo;
<strong>Controller:</strong>    Skeleton &raquo;
<strong>Action:</strong>        index-->

<table class="table table-responsive table-striped">
     <tr>
    <th>ID</th>
    <th>Nombre</th>   
    <th>Email</th>
    <th>RUT</th>
</tr>

<?php foreach ($proveedores as $valor): ?>

<tr>
        <td><?=$valor['id']?></td>   
        <td><?=$valor['nombre']?></td>  
        <td><?=$valor['email']?></td> 
        <td><?=$valor['rut']?></td> 
</tr>

<?php endforeach; ?>   

</table>

